### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by xAlexV** [Mosibi/whr_930#18]
Hi,

i’ve recently moved into the house and o try to automate/control everything with HA as much as possible. I have a whr 930 in the attic, but it’s quite hard to make a direct connection for it to my pi. 

Do you know if there is a way to make it work without the direct connection? Like having a WiFi adapter in the whr. 

Cheers,
Alexandru

**Comment by Mosibi** [comment]
Alexandru,

The most easy way would be if you have an extra pi with Wifi which you can connect to the WHR. Since the data is transferred over MQTT a direct connection to your pi with Home Assistant on it, is not needed.

You probably could also use something like a Raspberry Pi Zero 2 W, but personally I do not have experience with those boards yet.
